name: version
on:
  workflow_call:
    inputs:
      newversion:
        description: 'npm version [<newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease | from-git]'
        required: true
      preid:
        description: 'The "prerelease identifier" to use as a prefix for the "prerelease" part of a semver.'
        required: false
      github_token:
        description: 'Github token'
        required: true
      npm_token:
        description: 'NPM token'
        required: true

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - uses: skonves/npm-publish-version@main
        with:
          newversion: ${{ github.event.inputs.newversion }}
          preid: ${{ github.event.inputs.preid }}
          github_token: ${{ github.event.inputs.github_token }}
          npm_token: ${{ github.event.inputs.npm_token }}
